apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-console
  labels:
    app: openshift-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-console
  template:
    metadata:
      labels:
        app: openshift-console
    spec:
      serviceAccount: openshift-console
      containers:
      - name: openshift-console
        image: quay.io/openshift/origin-console:latest
        ports:
        - containerPort: 9000
        env:
        - name: BRIDGE_K8S_AUTH
          value: "bearer-token"
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          value: "change me to the token output of the script"
        - name: BRIDGE_K8S_MODE
          value: "off-cluster"
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: "change me to the output of the script"
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true"
        - name: BRIDGE_USER_AUTH
          value: "disabled"
        - name: NO_AT_BRIDGE
          value: "1"