apiVersion: v1
kind: Service
metadata:
  name: openshift-console
  labels:
    app.kubernetes.io/name: openshift-console
    app: openshift-console
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: openshift-console
